### ISSUE TITLE
de430.bsp was not found!

### ISSUE THREAD

**Issue by gravityguru** [Jagod101/OrbitalTrajectorySimulator#3]
After running orbital.py
Traceback (most recent call last):
  File "Orbital.py", line 187, in <module>
    main()
  File "Orbital.py", line 143, in main
    raise ValueError('de430.bsp was not found!')
ValueError: de430.bsp was not found!

**Comment by Z3DDev** [comment]
@gravityguru make sure you have downloaded the de430.bsp file which can be found through this link here https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/
